<!DOCTYPE html>
<html>

<head>
    <title>Excepciones</title>
</head>

<body>
    <script>
        const myError = new Error('My Error');

        try {
            // Aquí va el código que puede lanzar una excepción
            throw myError;
        } catch (error) {
            console.log(error.name);    // Esto imprimirá "Error"
            console.log(error.message); // Esto imprimirá "My Error"
            console.log(error.stack);   // Esto imprimirá la pila de llamadas en el momento en que se lanzó el error
        }
    </script>
</body>

</html>